import Head from "next/head"
import styles from "../styles/Home.module.css"
import LotteryEntrance from "../components/LotteryEntrance"
import Header from "../components/Header.js"
import { useMoralis } from "react-moralis"

export default function Home() {
    const { isWeb3Enabled, chainId } = useMoralis()
    return (
        <div className={styles.container}>
            <Head>
                <title>Smart Contract Lottery</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <LotteryEntrance />
        </div>
    )
}
